import type { ClassDefinition } from "../types";

export const druid: ClassDefinition = {
  id: "druid",
  name: "Druid",
  icon: "icons/classes/druid.jpg",
  playable: true,
  color: "#ff7c0a",
  spells: [
    {
      id: "remove-curse",
      name: "Remove Curse",
      icon: "icons/druid/remove-curse.jpg",
      targetMode: "ally",
      description: "Remove Curse effects from a teammate.",
      suggestedBindings: { player: "Shift+1", party1: "Shift+2", party2: "Shift+3" },
      enabledByDefault: true,
      dispels: ["curse"],
    },
    {
      id: "abolish-poison",
      name: "Abolish Poison",
      icon: "icons/druid/abolish-poison.jpg",
      targetMode: "ally",
      description: "Remove Poison effects from a teammate.",
      suggestedBindings: { player: "Ctrl+1", party1: "Ctrl+2", party2: "Ctrl+3" },
      enabledByDefault: true,
      dispels: ["poison"],
    },
    {
      id: "cyclone",
      name: "Cyclone",
      icon: "icons/druid/cyclone.jpg",
      targetMode: "arena",
      description: "Cyclone a specific arena enemy.",
      suggestedBindings: { arena1: "1", arena2: "2", arena3: "3" },
      enabledByDefault: true,
    },
    {
      id: "entangling-roots",
      name: "Entangling Roots",
      icon: "icons/druid/entangling-roots.jpg",
      targetMode: "arena",
      description: "Root a specific arena enemy.",
      suggestedBindings: { arena1: "Shift+Q", arena2: "Shift+W", arena3: "Shift+E" },
      enabledByDefault: true,
    },
    {
      id: "hibernate",
      name: "Hibernate",
      icon: "icons/druid/hibernate.jpg",
      targetMode: "arena",
      description: "Sleep a valid enemy target.",
      suggestedBindings: { arena1: "Ctrl+Q", arena2: "Ctrl+W", arena3: "Ctrl+E" },
      enabledByDefault: false,
    },
    {
      id: "faerie-fire",
      name: "Faerie Fire",
      icon: "icons/druid/faerie-fire.jpg",
      targetMode: "arena",
      description: "Prevent stealth and reduce armor on a specific enemy.",
      suggestedBindings: { arena1: "Alt+Q", arena2: "Alt+W", arena3: "Alt+E" },
      enabledByDefault: false,
    },
  ],
};
