import type { ClassDefinition } from "../types";

/**
 * WotLK 3.3.5a Mage training data.
 * Spell icons use the original client texture names and are bundled in public/icons.
 */
export const mage: ClassDefinition = {
  id: "mage",
  name: "Mage",
  icon: "icons/classes/mage.jpg",
  playable: true,
  color: "#69ccf0",
  spells: [
    {
      id: "frostbolt-rank-1",
      name: "Frostbolt (Rank 1)",
      icon: "icons/mage/frostbolt.jpg",
      targetMode: "arena",
      description: "Low-rank Frostbolt for slows and arena target control.",
      suggestedBindings: { arena1: "1", arena2: "2", arena3: "3" },
      enabledByDefault: true,
    },
    {
      id: "polymorph",
      name: "Polymorph",
      icon: "icons/mage/polymorph.jpg",
      targetMode: "arena",
      description: "Transform the selected arena enemy.",
      suggestedBindings: { arena1: "Shift+1", arena2: "Shift+2", arena3: "Shift+3" },
      enabledByDefault: true,
    },
    {
      id: "counterspell",
      name: "Counterspell",
      icon: "icons/mage/counterspell.jpg",
      targetMode: "arena",
      description: "Interrupt the selected arena enemy.",
      suggestedBindings: { arena1: "Ctrl+1", arena2: "Ctrl+2", arena3: "Ctrl+3" },
      enabledByDefault: true,
    },
    {
      id: "deep-freeze",
      name: "Deep Freeze",
      icon: "icons/mage/deep-freeze.jpg",
      targetMode: "arena",
      description: "Stun the selected arena enemy.",
      suggestedBindings: { arena1: "Alt+1", arena2: "Alt+2", arena3: "Alt+3" },
      enabledByDefault: true,
    },
    {
      id: "spellsteal",
      name: "Spellsteal",
      icon: "icons/mage/spellsteal.jpg",
      targetMode: "arena",
      description: "Steal a magic effect from the selected arena enemy.",
      suggestedBindings: { arena1: "Ctrl+Z", arena2: "Ctrl+X", arena3: "Ctrl+C" },
      enabledByDefault: false,
    },
    {
      id: "ice-lance",
      name: "Ice Lance",
      icon: "icons/mage/ice-lance.jpg",
      targetMode: "arena",
      description: "Instant Frost damage on a specific enemy.",
      suggestedBindings: { arena1: "Alt+Q", arena2: "Alt+W", arena3: "Alt+E" },
      enabledByDefault: false,
    },
    {
      id: "fire-blast",
      name: "Fire Blast",
      icon: "icons/mage/fire-blast.jpg",
      targetMode: "arena",
      description: "Instant Fire damage on a specific enemy.",
      suggestedBindings: { arena1: "Shift+A", arena2: "Shift+S", arena3: "Shift+D" },
      enabledByDefault: false,
    },
    {
      id: "scorch",
      name: "Scorch",
      icon: "icons/mage/scorch.jpg",
      targetMode: "arena",
      description: "Fast Fire cast on a specific enemy.",
      suggestedBindings: { arena1: "Ctrl+A", arena2: "Ctrl+S", arena3: "Ctrl+D" },
      enabledByDefault: false,
    },
    {
      id: "slow",
      name: "Slow",
      icon: "icons/mage/slow.jpg",
      targetMode: "arena",
      description: "Arcane movement and casting slow.",
      suggestedBindings: { arena1: "Alt+A", arena2: "Alt+S", arena3: "Alt+D" },
      enabledByDefault: false,
    },
    {
      id: "arcane-barrage",
      name: "Arcane Barrage",
      icon: "icons/mage/arcane-barrage.jpg",
      targetMode: "arena",
      description: "Instant Arcane damage on a specific enemy.",
      suggestedBindings: { arena1: "Q", arena2: "W", arena3: "E" },
      enabledByDefault: false,
    },
    {
      id: "frost-nova",
      name: "Frost Nova",
      icon: "icons/mage/frost-nova.jpg",
      targetMode: "arena",
      description: "Kept available for custom bind drills; disabled by default.",
      suggestedBindings: { arena1: "Shift+F", arena2: "Shift+G", arena3: "Shift+H" },
      enabledByDefault: false,
    },
    {
      id: "remove-curse",
      name: "Remove Curse",
      icon: "icons/mage/remove-curse.jpg",
      targetMode: "ally",
      description: "Optional Level 2 drill for Self, Party 1 and Party 2.",
      suggestedBindings: { player: "Alt+F1", party1: "Alt+F2", party2: "Alt+F3" },
      enabledByDefault: false,
      dispels: ["curse"],
    },
  ],
};
