import type { ClassDefinition } from "../types";

export const paladin: ClassDefinition = {
  id: "paladin",
  name: "Paladin",
  icon: "icons/classes/paladin.jpg",
  playable: true,
  color: "#f48cba",
  spells: [
    {
      id: "cleanse",
      name: "Cleanse",
      icon: "icons/paladin/cleanse.jpg",
      targetMode: "ally",
      description: "Remove Magic, Poison or Disease from a teammate.",
      suggestedBindings: { player: "Shift+1", party1: "Shift+2", party2: "Shift+3" },
      enabledByDefault: true,
      dispels: ["magic", "poison", "disease"],
    },
    {
      id: "hand-of-freedom",
      name: "Hand of Freedom",
      icon: "icons/paladin/hand-of-freedom.jpg",
      targetMode: "ally",
      description: "Freedom for Self, Party 1 or Party 2.",
      suggestedBindings: { player: "Alt+1", party1: "Alt+2", party2: "Alt+3" },
      enabledByDefault: true,
    },
    {
      id: "hand-of-protection",
      name: "Hand of Protection",
      icon: "icons/paladin/hand-of-protection.jpg",
      targetMode: "ally",
      description: "Physical immunity for a specific teammate.",
      suggestedBindings: { player: "Ctrl+1", party1: "Ctrl+2", party2: "Ctrl+3" },
      enabledByDefault: false,
    },
    {
      id: "hand-of-sacrifice",
      name: "Hand of Sacrifice",
      icon: "icons/paladin/hand-of-sacrifice.jpg",
      targetMode: "ally",
      description: "Damage-transfer utility for a specific teammate.",
      suggestedBindings: { player: "Shift+Q", party1: "Shift+W", party2: "Shift+E" },
      enabledByDefault: false,
    },
    {
      id: "hammer-of-justice",
      name: "Hammer of Justice",
      icon: "icons/paladin/hammer-of-justice.jpg",
      targetMode: "arena",
      description: "Stun a specific arena enemy.",
      suggestedBindings: { arena1: "Q", arena2: "W", arena3: "E" },
      enabledByDefault: true,
    },
    {
      id: "repentance",
      name: "Repentance",
      icon: "icons/paladin/repentance.jpg",
      targetMode: "arena",
      description: "Incapacitate a specific arena enemy.",
      suggestedBindings: { arena1: "Alt+Q", arena2: "Alt+W", arena3: "Alt+E" },
      enabledByDefault: true,
    },
  ],
};
