import type { ClassDefinition } from "../types";

export const priest: ClassDefinition = {
  id: "priest",
  name: "Priest",
  icon: "icons/classes/priest.jpg",
  playable: true,
  color: "#ffffff",
  spells: [
    {
      id: "dispel-magic-ally",
      name: "Dispel Magic (Ally)",
      icon: "icons/priest/dispel-magic.jpg",
      targetMode: "ally",
      description: "Remove Magic effects from Self, Party 1 or Party 2.",
      suggestedBindings: { player: "Shift+1", party1: "Shift+2", party2: "Shift+3" },
      enabledByDefault: true,
      dispels: ["magic"],
    },
    {
      id: "abolish-disease",
      name: "Abolish Disease",
      icon: "icons/priest/abolish-disease.jpg",
      targetMode: "ally",
      description: "Remove Disease effects from a teammate.",
      suggestedBindings: { player: "Ctrl+1", party1: "Ctrl+2", party2: "Ctrl+3" },
      enabledByDefault: false,
      dispels: ["disease"],
    },
    {
      id: "dispel-magic-enemy",
      name: "Dispel Magic (Offensive)",
      icon: "icons/priest/dispel-magic.jpg",
      targetMode: "arena",
      description: "Strip beneficial Magic from a specific enemy.",
      suggestedBindings: { arena1: "Ctrl+Q", arena2: "Ctrl+W", arena3: "Ctrl+E" },
      enabledByDefault: true,
    },
    {
      id: "silence",
      name: "Silence",
      icon: "icons/priest/silence.jpg",
      targetMode: "arena",
      description: "Silence a specific arena enemy.",
      suggestedBindings: { arena1: "Alt+1", arena2: "Alt+2", arena3: "Alt+3" },
      enabledByDefault: true,
    },
    {
      id: "psychic-horror",
      name: "Psychic Horror",
      icon: "icons/priest/psychic-horror.jpg",
      targetMode: "arena",
      description: "Horrify and disarm a specific enemy.",
      suggestedBindings: { arena1: "Shift+Q", arena2: "Shift+W", arena3: "Shift+E" },
      enabledByDefault: true,
    },
    {
      id: "mana-burn",
      name: "Mana Burn",
      icon: "icons/priest/mana-burn.jpg",
      targetMode: "arena",
      description: "Targeted mana-pressure drill.",
      suggestedBindings: { arena1: "Q", arena2: "W", arena3: "E" },
      enabledByDefault: false,
    },
    {
      id: "shadow-word-death",
      name: "Shadow Word: Death",
      icon: "icons/priest/shadow-word-death.jpg",
      targetMode: "arena",
      description: "Time the backlash near the end of an incoming CC cast.",
      suggestedBindings: { arena1: "1", arena2: "2", arena3: "3" },
      enabledByDefault: false,
      counterplay: {
        cueIds: ["polymorph", "fear"],
        castDurationMs: 1500,
        successWindowMs: 300,
      },
    },
  ],
};
