import type { ClassDefinition } from "../types";

/** WotLK 3.3.5a Rogue arena-target training data. */
export const rogue: ClassDefinition = {
  id: "rogue",
  name: "Rogue",
  icon: "icons/classes/rogue.jpg",
  playable: true,
  color: "#fff468",
  spells: [
    {
      id: "kick",
      name: "Kick",
      icon: "icons/rogue/kick.jpg",
      targetMode: "arena",
      description: "Interrupt a specific arena enemy.",
      suggestedBindings: { arena1: "Ctrl+1", arena2: "Ctrl+2", arena3: "Ctrl+3" },
      enabledByDefault: true,
    },
    {
      id: "blind",
      name: "Blind",
      icon: "icons/rogue/blind.jpg",
      targetMode: "arena",
      description: "Blind a specific arena enemy.",
      suggestedBindings: { arena1: "Shift+1", arena2: "Shift+2", arena3: "Shift+3" },
      enabledByDefault: true,
    },
    {
      id: "sap",
      name: "Sap",
      icon: "icons/rogue/sap.jpg",
      targetMode: "arena",
      description: "Sap a specific arena enemy without changing target.",
      suggestedBindings: { arena1: "Alt+1", arena2: "Alt+2", arena3: "Alt+3" },
      enabledByDefault: true,
    },
    {
      id: "kidney-shot",
      name: "Kidney Shot",
      icon: "icons/rogue/kidney-shot.jpg",
      targetMode: "arena",
      description: "Stun a specific arena enemy with Kidney Shot.",
      suggestedBindings: { arena1: "1", arena2: "2", arena3: "3" },
      enabledByDefault: true,
    },
    {
      id: "shadowstep",
      name: "Shadowstep",
      icon: "icons/rogue/shadowstep.jpg",
      targetMode: "arena",
      description: "Shadowstep to a specific arena enemy.",
      suggestedBindings: { arena1: "Ctrl+Q", arena2: "Ctrl+W", arena3: "Ctrl+E" },
      enabledByDefault: true,
    },
    {
      id: "shadowstep-kick",
      name: "Shadowstep + Kick",
      icon: "icons/rogue/kick.jpg",
      targetMode: "arena",
      description: "One arena-target macro: step to the enemy and interrupt their cast.",
      suggestedBindings: { arena1: "Ctrl+Shift+1", arena2: "Ctrl+Shift+2", arena3: "Ctrl+Shift+3" },
      enabledByDefault: true,
      macroSteps: ["Shadowstep", "Kick"],
    },
    {
      id: "shadowstep-blind",
      name: "Shadowstep + Blind",
      icon: "icons/rogue/blind.jpg",
      targetMode: "arena",
      description: "One arena-target macro: step to the enemy and Blind without changing target.",
      suggestedBindings: { arena1: "Ctrl+Alt+1", arena2: "Ctrl+Alt+2", arena3: "Ctrl+Alt+3" },
      enabledByDefault: true,
      macroSteps: ["Shadowstep", "Blind"],
    },
    {
      id: "shadowstep-cheap-shot",
      name: "Shadowstep + Cheap Shot",
      icon: "icons/rogue/cheap-shot.jpg",
      targetMode: "arena",
      description: "One arena-target macro: step to the enemy and Cheap Shot from stealth or Shadow Dance.",
      suggestedBindings: { arena1: "Ctrl+Alt+Shift+1", arena2: "Ctrl+Alt+Shift+2", arena3: "Ctrl+Alt+Shift+3" },
      enabledByDefault: true,
      macroSteps: ["Shadowstep", "Cheap Shot"],
    },
    {
      id: "gouge",
      name: "Gouge",
      icon: "icons/rogue/gouge.jpg",
      targetMode: "arena",
      description: "Optional target-specific Gouge drill.",
      suggestedBindings: { arena1: "Shift+Q", arena2: "Shift+W", arena3: "Shift+E" },
      enabledByDefault: false,
    },
    {
      id: "shiv",
      name: "Shiv",
      icon: "icons/rogue/shiv.jpg",
      targetMode: "arena",
      description: "Optional Shiv drill for poison application and control.",
      suggestedBindings: { arena1: "Alt+Q", arena2: "Alt+W", arena3: "Alt+E" },
      enabledByDefault: false,
    },
    {
      id: "dismantle",
      name: "Dismantle",
      icon: "icons/rogue/dismantle.jpg",
      targetMode: "arena",
      description: "Disarm a specific arena enemy.",
      suggestedBindings: { arena1: "Ctrl+Shift+Q", arena2: "Ctrl+Shift+W", arena3: "Ctrl+Shift+E" },
      enabledByDefault: false,
    },
    {
      id: "garrote",
      name: "Garrote",
      icon: "icons/rogue/garrote.jpg",
      targetMode: "arena",
      description: "Open on a specific arena enemy with Garrote.",
      suggestedBindings: { arena1: "Ctrl+Alt+Q", arena2: "Ctrl+Alt+W", arena3: "Ctrl+Alt+E" },
      enabledByDefault: false,
    },
    {
      id: "deadly-throw",
      name: "Deadly Throw",
      icon: "icons/rogue/deadly-throw.jpg",
      targetMode: "arena",
      description: "Use Deadly Throw on a specific arena enemy.",
      suggestedBindings: { arena1: "Alt+Shift+1", arena2: "Alt+Shift+2", arena3: "Alt+Shift+3" },
      enabledByDefault: false,
    },
  ],
};
